ServerEvents.tags('block', event => {
	event.get('minecraft:needs_stone_tool')
		.remove('minecraft:copper_ore')
		.remove('minecraft:deepslate_copper_ore')
		.remove('minecraft:raw_copper_block')

		.remove('minecraft:copper_block')
	    .remove('minecraft:exposed_copper')
	    .remove('minecraft:weathered_copper')
	    .remove('minecraft:oxidized_copper')

        .remove('minecraft:chiseled_copper')
        .remove('minecraft:exposed_chiseled_copper')
        .remove('minecraft:weathered_chiseled_copper')
        .remove('minecraft:oxidized_chiseled_copper')
        
        .remove('minecraft:copper_grate')
        .remove('minecraft:exposed_copper_grate')
        .remove('minecraft:weathered_copper_grate')
        .remove('minecraft:oxidized_copper_grate')

	    .remove('minecraft:cut_copper')
	    .remove('minecraft:exposed_cut_copper')
	    .remove('minecraft:weathered_cut_copper')
	    .remove('minecraft:oxidized_cut_copper')

	    .remove('minecraft:cut_copper_stairs')
	    .remove('minecraft:exposed_cut_copper_stairs')
	    .remove('minecraft:weathered_cut_copper_stairs')
	    .remove('minecraft:oxidized_cut_copper_stairs')

	    .remove('minecraft:cut_copper_slab')
	    .remove('minecraft:exposed_cut_copper_slab')
	    .remove('minecraft:weathered_cut_copper_slab')
	    .remove('minecraft:oxidized_cut_copper_slab')

        .remove('minecraft:copper_door')
        .remove('minecraft:exposed_copper_door')
        .remove('minecraft:weathered_copper_door')
        .remove('minecraft:oxidized_copper_door')
        
	    .remove('minecraft:waxed_copper_block')
	    .remove('minecraft:waxed_exposed_copper')
	    .remove('minecraft:waxed_weathered_copper')
	    .remove('minecraft:waxed_oxidized_copper')

        .remove('minecraft:waxed_chiseled_copper')
        .remove('minecraft:waxed_exposed_chiseled_copper')
        .remove('minecraft:waxed_weathered_chiseled_copper')
        .remove('minecraft:waxed_oxidized_chiseled_copper')
        
        .remove('minecraft:waxed_copper_grate')
        .remove('minecraft:waxed_exposed_copper_grate')
        .remove('minecraft:waxed_weathered_copper_grate')
        .remove('minecraft:waxed_oxidized_copper_grate')

	    .remove('minecraft:waxed_cut_copper')
	    .remove('minecraft:waxed_exposed_cut_copper')
	    .remove('minecraft:waxed_weathered_cut_copper')
	    .remove('minecraft:waxed_oxidized_cut_copper')
        
	    .remove('minecraft:waxed_cut_copper_stairs')
	    .remove('minecraft:waxed_exposed_cut_copper_stairs')
	    .remove('minecraft:waxed_weathered_cut_copper_stairs')
	    .remove('minecraft:waxed_oxidized_cut_copper_stairs')

	    .remove('minecraft:waxed_cut_copper_slab')
	    .remove('minecraft:waxed_exposed_cut_copper_slab')
	    .remove('minecraft:waxed_weathered_cut_copper_slab')
	    .remove('minecraft:waxed_oxidized_cut_copper_slab')

        .remove('minecraft:waxed_copper_door')
        .remove('minecraft:waxed_exposed_copper_door')
        .remove('minecraft:waxed_weathered_copper_door')
        .remove('minecraft:waxed_oxidized_copper_door')
        
        .remove('create:copper_shingles')
	    .remove('create:exposed_copper_shingles')
	    .remove('create:weathered_copper_shingles')
	    .remove('create:oxidized_copper_shingles')
	    .remove('create:copper_shingle_slab')
	    .remove('create:exposed_copper_shingle_slab')
	    .remove('create:weathered_copper_shingle_slab')
	    .remove('create:oxidized_copper_shingle_slab')
	    .remove('create:copper_shingle_stairs')
	    .remove('create:exposed_copper_shingle_stairs')
	    .remove('create:weathered_copper_shingle_stairs')
	    .remove('create:oxidized_copper_shingle_stairs')
	    .remove('create:waxed_copper_shingles')
	    .remove('create:waxed_exposed_copper_shingles')
	    .remove('create:waxed_weathered_copper_shingles')
	    .remove('create:waxed_oxidized_copper_shingles')
	    .remove('create:waxed_copper_shingle_slab')
	    .remove('create:waxed_exposed_copper_shingle_slab')
	    .remove('create:waxed_weathered_copper_shingle_slab')
	    .remove('create:waxed_oxidized_copper_shingle_slab')
	    .remove('create:waxed_copper_shingle_stairs')
	    .remove('create:waxed_exposed_copper_shingle_stairs')
	    .remove('create:waxed_weathered_copper_shingle_stairs')
	    .remove('create:waxed_oxidized_copper_shingle_stairs')
	    .remove('create:copper_tiles')
	    .remove('create:exposed_copper_tiles')
	    .remove('create:weathered_copper_tiles')
	    .remove('create:oxidized_copper_tiles')
	    .remove('create:copper_tile_slab')
	    .remove('create:exposed_copper_tile_slab')
	    .remove('create:weathered_copper_tile_slab')
	    .remove('create:oxidized_copper_tile_slab')
	    .remove('create:copper_tile_stairs')
	    .remove('create:exposed_copper_tile_stairs')
	    .remove('create:weathered_copper_tile_stairs')
	    .remove('create:oxidized_copper_tile_stairs')
	    .remove('create:waxed_copper_tiles')
	    .remove('create:waxed_exposed_copper_tiles')
	    .remove('create:waxed_weathered_copper_tiles')
	    .remove('create:waxed_oxidized_copper_tiles')
	    .remove('create:waxed_copper_tile_slab')
	    .remove('create:waxed_exposed_copper_tile_slab')
	    .remove('create:waxed_weathered_copper_tile_slab')
	    .remove('create:waxed_oxidized_copper_tile_slab')
	    .remove('create:waxed_copper_tile_stairs')
	    .remove('create:waxed_exposed_copper_tile_stairs')
	    .remove('create:waxed_weathered_copper_tile_stairs')
	    .remove('create:waxed_oxidized_copper_tile_stairs')
        
        .remove('blockbox:copper_bars')
        .remove('blockbox:exposed_copper_bars')
        .remove('blockbox:weathered_copper_bars')
        .remove('blockbox:oxidized_copper_bars')
        
        .remove('blockbox:waxed_copper_bars')
        .remove('blockbox:waxed_exposed_copper_bars')
        .remove('blockbox:waxed_weathered_copper_bars')
        .remove('blockbox:waxed_oxidized_copper_bars')

        .remove('blockbox:copper_pillar')
        .remove('blockbox:exposed_copper_pillar')
        .remove('blockbox:weathered_copper_pillar')
        .remove('blockbox:oxidized_copper_pillar')

        .remove('blockbox:waxed_copper_pillar')
        .remove('blockbox:waxed_exposed_copper_pillar')
        .remove('blockbox:waxed_weathered_copper_pillar')
        .remove('blockbox:waxed_oxidized_copper_pillar')
})
