ItemEvents.modification(event => {
	function maxDura(x, q) {
		event.modify(x, item => {item.maxDamage = q})
	}
	
	maxDura('minecraft:shears', 384)
	maxDura('minecraft:fishing_rod', 128)
	maxDura('minecraft:carrot_on_a_stick', 128)
	maxDura('minecraft:warped_fungus_on_a_stick', 128)
	maxDura('supplementaries:wrench', 384)
	maxDura('supplementaries:flute', 128)
	maxDura('minecraft:brush', 128)
	maxDura('minecraft:turtle_helmet', 320)
	maxDura('minecraft:trident', 750)

	
	maxDura('minecraft:wooden_pickaxe', 150)
	maxDura('minecraft:wooden_axe', 150)
	maxDura('minecraft:wooden_shovel', 150)
	maxDura('minecraft:wooden_hoe', 150)
	maxDura('minecraft:wooden_sword', 150)
	maxDura('farmersdelight:flint_knife', 150)
	maxDura('minecraft:flint_and_steel', 150)
	maxDura('supplementaries:flute', 256)
	maxDura('supplementaries:slingshot', 256)
	maxDura('minecraft:bow', 150)
	

	maxDura('minecraft:stone_pickaxe', 350)
	maxDura('minecraft:stone_axe', 350)
	maxDura('minecraft:stone_shovel', 350)
	maxDura('minecraft:stone_hoe', 350)
	maxDura('minecraft:stone_sword', 350)


	maxDura('minecraft:golden_pickaxe',406)
	maxDura('minecraft:golden_axe', 406)
	maxDura('minecraft:golden_shovel', 406)
	maxDura('minecraft:golden_hoe', 406)
	maxDura('minecraft:golden_sword', 406)
	maxDura('farmersdelight:golden_knife', 406)
	maxDura('minecraft:golden_helmet', 384)
	maxDura('minecraft:golden_chestplate', 384)
	maxDura('minecraft:golden_leggings', 384)
	maxDura('minecraft:golden_boots', 384)

	maxDura('minecraft:iron_pickaxe', 512)
	maxDura('minecraft:iron_axe', 512)
	maxDura('minecraft:iron_shovel', 512)
	maxDura('minecraft:iron_hoe', 512)
	maxDura('minecraft:iron_sword', 512)
	maxDura('minecraft:iron_helmet', 320)
	maxDura('minecraft:iron_chestplate', 320)
	maxDura('minecraft:iron_leggings', 320)
	maxDura('minecraft:iron_boots', 320)
	maxDura('minecraft:shield', 512)

	maxDura('minecraft:diamond_pickaxe', 2000)
	maxDura('minecraft:diamond_axe', 2000)
	maxDura('minecraft:diamond_shovel', 2000)
	maxDura('minecraft:diamond_hoe', 2000)
	maxDura('minecraft:diamond_sword', 2000)
	maxDura('farmersdelight:diamond_knife', 2000)
	maxDura('minecraft:diamond_helmet', 700)
	maxDura('minecraft:diamond_chestplate', 700)
	maxDura('minecraft:diamond_leggings', 700)
	maxDura('minecraft:diamond_boots', 700)

	maxDura('minecraft:netherite_pickaxe', 2500)
	maxDura('minecraft:netherite_axe', 2500)
	maxDura('minecraft:netherite_shovel', 2500)
	maxDura('minecraft:netherite_hoe', 2500)
	maxDura('minecraft:netherite_sword', 2500)
	maxDura('farmersdelight:netherite_knife', 2500)
	maxDura('minecraft:netherite_helmet', 1175)
	maxDura('minecraft:netherite_chestplate', 1175)
	maxDura('minecraft:netherite_leggings', 1175)
	maxDura('minecraft:netherite_boots', 1175)

})